all:
	cd /home/bruno/Code/Java/desafio-poo-dio/src ; /usr/bin/env /usr/lib/jvm/java-21-openjdk-amd64/bin/java -XX:+ShowCodeDetailsInExceptionMessages -cp /home/bruno/.config/Code/User/workspaceStorage/891b421b0800935c04f9ad852e74b3e0/redhat.java/jdt_ws/src_6604ce7d/bin Main 

